apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-nodejs
    app.kubernetes.io/part-of: test-application
  name: devfile-nodejs
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: devfile-nodejs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: devfile-nodejs
    spec:
      containers:
      - image: quay.io/karthik_jk/devfile-nodejs@sha256:da76145f41cd63504f90da49d390f565e32ea31cd961f5fca0b9aba1712c151d
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
